name: clean_arc
description: It is a tool to create clean architecture modules structure folders.
version: 1.0.2
homepage: https://github.com/ArielFarias/clean-arc

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.3.0
  pub_api_client: ^2.6.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0

executables:
  clean_arc:
